[pyprland]
plugins = [
    "scratchpads",
    "expose",
    "shift_monitors",
    #    "workspaces_follow_focus"
]

[scratchpads.term]
animation = "fromTop"
command = "~/.config/hypr/scripts/term_exec.sh --app-id hss-scratchpad --title Scratchpad -- bash"
class = "hss-scratchpad"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50
unfocus = "hide"

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "40% 30%"
position = "59% 4%"
unfocus = "hide"
lazy = true