# Check monitor names (e.g. DP-1, HDMI-A-1) with: `hyprctl monitors`
# Example single monitor configuration:
# monitor=DP-1,2560x1440@144,0x0,1
# workspace=1,monitor:DP-1,default:true

# Example dual monitor configuration:
# monitor=DP-1,2560x1440@144,0x0,1
# monitor=HDMI-A-1,1920x1080@60,2560x0,1
# workspace=1,monitor:DP-1,default:true
# workspace=2,monitor:HDMI-A-1
